version: '3.8'

services:
  postgres-dwh:
    image: postgres:15-alpine
    container_name: postgres-dwh
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dwh}
      POSTGRES_USER: ${POSTGRES_USER:-dwh}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dwh}
    ports:
      - 5432:5432
    volumes:
      - postgres-dwh-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dwh} -d ${POSTGRES_DB:-dwh}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      mlops-k6-network:

volumes:
  postgres-dwh-volume:
    driver: ${DRIVER:-local}

networks:
  mlops-k6-network:
    external: true
